yaml-testsuite implementation
kubkon/zig-yaml pull request #39
Opened 2024-06-09 04:36 UTC by sencrash

Resolves #16 

Adds yaml-testsuite as a submodule and enables generating and running the tests with the `-Denable-spec-tests` flag

Currently the testrunner misreports the number of passed testcases (related to ziglang/zig#1356)

2024-09-06 11:51 UTC, sencrash commented
Is there anything I can do to get this merged?

2024-10-21 11:22 UTC, kubkon requested changes
Thank you for this and apologies for the wait. Would you mind rebasing on top of latest `main` and making sure everything still builds? Also, is it possible to enable testing of the spec on every CI run?

2024-10-22 10:26 UTC, sencrash commented
> Thank you for this and apologies for the wait. Would you mind rebasing on top of latest `main` and making sure everything still builds? Also, is it possible to enable testing of the spec on every CI run?

Added the spec tests as a CI job, but assert crashes the testrunner so we can only really look at the overall pass/fail

2024-12-20 19:27 UTC, kubkon commented
Exciting! I finally have some time to look into it and so will do my best to work with you on getting it merged in the coming days. Sorry for the wait!

2024-12-20 23:05 UTC, merged