Allow commas in unquoted string + empty map
kubkon/zig-yaml pull request #42
Opened 2024-09-03 11:36 UTC by gwenzek

Hi Jakub,
thanks for the lib.

I found two minor issues with the libraries:

- `,` is a valid character for unquoted string, except in flow

From: https://yaml.org/spec/1.2.2/#733-plain-style
**inside** flow collections, plain scalars must not contain the “[”, “]”, “{”, “}” and “,” characters.
To handle this the tokenizer need to tracks if it's within a flow or not.

- `{}` is a valid map.

I can split the PR in two if you prefer, but also the commits are easy to review independently.

2024-09-03 11:39 UTC, gwenzek commented on src/parse.zig
> +                    log.err("Unhandled token in map: {}", .{key});
let me know if you find this is too much

2024-10-21 11:11 UTC, kubkon commented on src/parse.zig
> +                    log.err("Unhandled token in map: {}", .{key});
It's fine but I think if we had some error reporting layer setup it would have been even better.

2024-10-21 11:14 UTC, kubkon requested changes
Thanks! I've got some questions if you wouldn't mind answering them and helping me to understand the changes better.

2024-10-21 11:14 UTC, kubkon commented on src/Tokenizer.zig
> +in_flow: usize = 0,
How come it's not enough for `in_flow` to be a bool?

2024-11-19 21:45 UTC, lunjon commented
Great work! I think there's also a problem when parsing unquoted strings containing colon. For instance, the following currently fails for me:

```yaml
key: a::b
```

2024-11-20 15:43 UTC, gwenzek commented on src/Tokenizer.zig
> +in_flow: usize = 0,
this handle nesting of list/mapping. If there are several nested list, I need to remember how many closing tag I need to see before setting "in_flow" to false.

2024-11-20 15:44 UTC, gwenzek commented
@kubkon sorry, I forgot about this PR, I answered your question


> I think there's also a problem when parsing unquoted strings containing colon.

@lunjon  do you mean a problem in this branch or on main ?

2024-11-20 17:42 UTC, lunjon commented
> @kubkon sorry, I forgot about this PR, I answered your question
> 
> 
> > I think there's also a problem when parsing unquoted strings containing colon.
> 
> @lunjon  do you mean a problem in this branch or on main ?

In main, and I believe the issue could be related to the issue this PR fixes.

2024-11-21 08:23 UTC, gwenzek commented
@lunjon it's not directly related, you can see previous PR #27 or my own more complete implem https://github.com/gwenzek/zig-yaml/pull/1

2024-11-21 08:27 UTC, lunjon commented
> @lunjon it's not directly related, you can see previous PR #27 or my own more complete implem [gwenzek#1](https://github.com/gwenzek/zig-yaml/pull/1)

Oh I see. Is there any plans to integrate these changes to main anytime soon?

2024-11-21 17:49 UTC, kubkon approved these changes
Thanks!

2024-11-21 17:50 UTC, merged